version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
    restart: unless-stopped
