version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123
    deploy:
      resources:
      
        limits:
          cpus: '2.0'       # NiFi ne prendra 2 cœur CPU max
          memory: 4G
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
    restart: unless-stopped
